version: "3.7"

services:

  jenkins:
    image: <>
    volumes:
      - /mnt/<>
    deploy:
      placement:
        constraints:
          - node.hostname == qoffee
      restart_policy:
        condition: on-failure
    networks:
      - backend
    environment:
      HETZNER_AUTH_API_TOKEN:
